import pandas as pd
import os
from datetime import datetime

class ReportGenerator:
    """
    Generates professional reports for Automation/ETL runs.
    Supports:
    1. HTML Summary Reports (Executive View)
    2. Excel Detailed Reports (Debug/Developer View)
    """

    def __init__(self, output_dir='reports'):
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_html_report(self, run_metadata, validation_results, filename="execution_summary.html"):
        """
        Creates a styled HTML report.
        run_metadata: dict (e.g., {'Env': 'QA', 'Date': '...'})
        validation_results: list of dicts (e.g., [{'Test': 'Data Diff', 'Status': 'PASS', 'Message': '...'}])
        """
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', sans-serif; margin: 20px; }}
                h1 {{ color: #2c3e50; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
                th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #34495e; color: white; }}
                .pass {{ color: green; font-weight: bold; }}
                .fail {{ color: red; font-weight: bold; }}
                .metadata {{ background: #ecf0f1; padding: 15px; border-radius: 5px; }}
            </style>
        </head>
        <body>
            <h1>Automation Execution Report</h1>
            <div class="metadata">
                <h3>Run Details</h3>
                <ul>
                    {''.join([f"<li><strong>{k}:</strong> {v}</li>" for k, v in run_metadata.items()])}
                </ul>
            </div>
            
            <h3>Validation Results</h3>
            <table>
                <tr>
                    <th>Test Case</th>
                    <th>Status</th>
                    <th>Details</th>
                </tr>
        """
        
        for res in validation_results:
            status_class = "pass" if res['Status'] == 'PASS' else "fail"
            html_content += f"""
                <tr>
                    <td>{res['Test']}</td>
                    <td class="{status_class}">{res['Status']}</td>
                    <td>{res['Message']}</td>
                </tr>
            """

        html_content += """
            </table>
            <p>Generated by Automation Framework</p>
        </body>
        </html>
        """
        
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(html_content)
        print(f"[*] HTML Report generated: {filepath}")

    def generate_excel_failure_report(self, failed_rows_df, filename="failures.xlsx"):
        """
        Dumps failure records (DataFrames) to Excel for manual analysis.
        """
        if failed_rows_df is None or failed_rows_df.empty:
            print("[*] No failures data to report.")
            return

        filepath = os.path.join(self.output_dir, filename)
        try:
            # Requires openpyxl installed
            failed_rows_df.to_excel(filepath, index=False)
            print(f"[*] Excel Failure Report generated: {filepath}")
        except ModuleNotFoundError:
             print("[!] 'openpyxl' module not found. Skipping Excel generation.")
        except Exception as e:
            print(f"[!] Failed to generate Excel report: {str(e)}")
